
services:
  nmap:
    image: uzyexe/nmap
    container_name: nmap_scanner
    command: ["nmap", "-sV", "target-ip"]  # Replace "target-ip" with a dynamic input
    networks:
      - security_net

  openvas:
    image: mikesplain/openvas
    container_name: openvas_scanner
    ports:
      - "9392:9392"  # OpenVAS Web UI
    networks:
      - security_net

  metasploit:
    image: metasploitframework/metasploit-framework
    container_name: metasploit
    tty: true
    networks:
      - security_net

  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: security_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - security_net

  ai_model:
    build: ./ai_model
    container_name: ai_classifier
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - security_net

  frontend:
    build: ./frontend
    container_name: security_dashboard
    ports:
      - "3000:3000"
    depends_on:
      - ai_model
    networks:
      - security_net

networks:
  security_net:

volumes:
  pgdata: